@startuml
left to right direction
actor Consumidor
actor Produtor
actor Cooperativa

rectangle "Aplicação Web" {
  Consumidor -- (Buscar Produtos)
  Consumidor -- (Adicionar ao Carrinho)
  Consumidor -- (Finalizar Pedido)
  Consumidor -- (Retirar Pedido)

  Produtor -- (Cadastrar Produtos)
  Produtor -- (Gerenciar Pedidos)
  Produtor -- (Entregar Pedidos)

  Cooperativa -- (Gerenciar Usuários)
  Cooperativa -- (Enviar Avisos Gerais)
  Cooperativa -- (Entregar Pedidos)
}

(Adicionar ao Carrinho) .> (Buscar Produtos) : extends
(Finalizar Pedido) .> (Adicionar ao Carrinho) : extends
@enduml