@startuml
skinparam actorStyle awesome

left to right direction
actor Consumidor #00EE99
actor Produtor #green
actor Cooperativa <<Admin>> #0064FF
actor Usuário #ddd

  Usuário -- (Edita perfil)
  Usuário -- (Cria conta)
  Usuário -- (Faz Login/logout)

  Consumidor -- (Pedido) : Cria, acompanha, edita, cancela, retira
  Produtor -- (Produtos): Cria, edita, remove

  Produtor -- (Pedido) : Gerencia, entrega
  (Pedido) -- Cooperativa: entrega

  Cooperativa -- (Gerencia Usuário)

  Consumidor <. Usuário : extends
  Produtor <. Consumidor : extends
  Cooperativa <. Usuário : extends
@enduml