@startuml

class OrderController implements CoreController {}
class OrderService implements CoreService {}
class OrderRepository implements CoreRepository {}

class Order <<model>> {}
class Address <<model>> {}
class Product <<model>> {}
class User <<model>> {}

' Relationships
OrderController --> OrderService : access
OrderService --> OrderRepository : manipulate
OrderRepository --> Order : based on
User --> Order : make
Order --> Address : has
Order --> Product : contains
Product --> User : belongs


note as N1
Core Interfaces
./CoreInterfaces.puml

Diagramas de classes
../entities
end note

@enduml