@startuml

class UserController implements CoreController {}
class UserService implements CoreService {}
class UserRepository implements CoreRepository {}

class User <<model>> {}
class Address <<model>> {}
class Product <<model>> {}

' Relationships
UserController --> UserService : access
UserService --> UserRepository : manipulate
UserRepository --> User : based on
UserRepository --> Address : has
UserRepository --> Product : contains

note as N1
See Core Interfaces
./CoreInterfaces.puml

See Models class diagrams on
../entities
end note

@enduml