@startuml
start
repeat
    :Buscar produto;
    if (Produto encontrado?) then (Não)
        :Produto não encontrado;
        stop
    else (Sim)
        :Adicionar ao carrinho;
    endif
repeat while (Deseja finalizar compra?) is (Não) not (Sim)
    :Finalizar pedido;
    :Pedido em preparação;
    if (Local e horario de retirada?) then (No produtor)
      :Consumidor retira o pedido no produtor;
      end
    else (Na cooperativa)
      :Produtor entrega o pedido na cooperativa;
      :Consumidor retira o pedido na cooperativa;
      end
    endif
@enduml